name: "PUML to PNG Commit & PR"
description: "Generates PNG from all PUML files found in a PR diff, commits and posts to PR"
branding:
  icon: "image"
  color: "orange"
inputs:
  botEmail:
    description: "E-mail address for git commit"
    required: true
  botGithubToken:
    description: "token of GitHub to commit"
    required: false
  enableReviewComment:
    description: "whether post review comment or not"
    required: false
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
