name: "Generate and Commit PlantUML Diagrams"
description: "generate from puml files to png files, and commit."
branding:
  icon: "image"
  color: "orange"
inputs:
  botEmail:
    description: "E-mail address for git commit"
    required: true
  botGithubToken:
    description: "token of GitHub to commit"
    required: false
  enableReviewComment:
    description: "whether post review comment or not"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
