name: generate and commit PlantUML diagrams
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate and commit diagrams
        uses: zaphiro-technologies/commit-plantuml-action@${{ github.head_ref }}
        with:
          botEmail: ${{ secrets.BOT_EMAIL }}
          botGithubToken: ${{ secrets.GITHUB_TOKEN }}
          enableReviewComment: true
          installGoogleFont: Barlow
